# Generated by Django 5.1.5 on 2025-01-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_document_flashcard_mcq_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
