# Generated by Django 5.1.5 on 2025-08-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_document_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='easiness',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='interval',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='next_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='repetitions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='times_shown',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['document', 'next_review_at'], name='API_flashca_documen_50099b_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(fields=['document', 'status'], name='API_flashca_documen_b2ebc6_idx'),
        ),
    ]
