# Generated by Django 5.1.5 on 2025-09-03 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_cloze_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeynmanAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('tier', models.CharField(blank=True, default='', max_length=20)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('key_points_coverage', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='cloze',
            new_name='API_cloze_documen_c785bb_idx',
            old_name='API_cloze_document_idx',
        ),
        migrations.RenameIndex(
            model_name='feynman',
            new_name='API_feynman_documen_fca409_idx',
            old_name='API_feynman_document_idx',
        ),
        migrations.AddField(
            model_name='feynmanattempt',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feynman_attempts', to='API.document'),
        ),
        migrations.AddField(
            model_name='feynmanattempt',
            name='feynman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='API.feynman'),
        ),
        migrations.AddField(
            model_name='feynmanattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feynman_attempts', to='API.user'),
        ),
        migrations.AddIndex(
            model_name='feynmanattempt',
            index=models.Index(fields=['document', 'user', 'feynman'], name='API_feynman_documen_6147ef_idx'),
        ),
        migrations.AddIndex(
            model_name='feynmanattempt',
            index=models.Index(fields=['score'], name='API_feynman_score_179203_idx'),
        ),
    ]
