# Generated by Django 5.1.5 on 2026-04-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_feynmanattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='source_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('transcript', 'Transcript')], default='pdf', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
