# Generated by Django 5.1.15 on 2026-07-31 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_document_source_type_alter_document_pdf_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLLMSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', 'Gemini'), ('claude', 'Claude (Anthropic)'), ('openai', 'OpenAI'), ('ollama', 'Ollama'), ('nvidia_nim', 'Nvidia NIM'), ('openrouter', 'OpenRouter')], default='gemini', max_length=32)),
                ('encrypted_api_key', models.TextField(blank=True, default='')),
                ('base_url', models.CharField(blank=True, default='', max_length=500)),
                ('model_name', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm_settings', to='API.user')),
            ],
        ),
    ]
