# Generated by Django 5.1.5 on 2026-08-03 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_userllmsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveIntegerField(default=1)),
                ('text', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='#FDE047', max_length=32)),
                ('rects', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='API.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_highlights', to='API.user')),
            ],
            options={
                'ordering': ['page', 'created_at'],
                'indexes': [models.Index(fields=['document', 'page'], name='API_documen_documen_77d1a2_idx')],
            },
        ),
    ]
