# Generated by Django 5.1.5 on 2026-08-04 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_documenthighlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='kind',
            field=models.CharField(choices=[('document', 'Document'), ('book', 'Book'), ('chapter', 'Chapter')], default='document', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='page_end',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='page_start',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='API.document'),
        ),
    ]
