# Generated by Django 5.1.5 on 2026-08-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_document_kind_document_page_end_document_page_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='source_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
