# Generated by Django 5.1.5 on 2026-08-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_user_last_active_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
