# Generated by Django 5.1.5 on 2026-04-22 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('API', '0009_document_source_type_alter_document_pdf_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('recording', 'Recording'), ('transcribing', 'Transcribing'), ('ready', 'Ready'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='recording', max_length=20)),
                ('language', models.CharField(default='es', max_length=8)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='class_audio/')),
                ('transcript_text', models.TextField(blank=True, default='')),
                ('source_meta', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_sessions', to='API.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_sessions', to='API.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('start_sec', models.FloatField(blank=True, null=True)),
                ('end_sec', models.FloatField(blank=True, null=True)),
                ('speaker_label', models.CharField(blank=True, default='', max_length=64)),
                ('text', models.TextField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='CLASSROOM.classsession')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['user', 'status'], name='CLASSROOM_c_user_id_6fa2d9_idx'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['created_at'], name='CLASSROOM_c_created_aaae1c_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptsegment',
            index=models.Index(fields=['class_session', 'sequence'], name='CLASSROOM_t_class_s_b11fec_idx'),
        ),
        migrations.AddConstraint(
            model_name='transcriptsegment',
            constraint=models.UniqueConstraint(fields=('class_session', 'sequence'), name='uniq_session_segment_sequence'),
        ),
    ]
