# Generated by Django 5.1.5 on 2026-04-24 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_document_source_type_alter_document_pdf_file_and_more'),
        ('CLASSROOM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='status',
            field=models.CharField(choices=[('recording', 'Recording'), ('stopped', 'Stopped'), ('transcribing', 'Transcribing'), ('ready', 'Ready'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='recording', max_length=20),
        ),
        migrations.CreateModel(
            name='ClassSessionFeynman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('key_points', models.JSONField(default=list)),
                ('reference', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feynmans', to='CLASSROOM.classsession')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSessionFeynmanAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('tier', models.CharField(blank=True, default='', max_length=20)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('key_points_coverage', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feynman_attempts', to='CLASSROOM.classsession')),
                ('feynman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='CLASSROOM.classsessionfeynman')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_feynman_attempts', to='API.user')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSessionMCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('option_1', models.CharField(max_length=255)),
                ('option_2', models.CharField(max_length=255)),
                ('option_3', models.CharField(max_length=255)),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcqs', to='CLASSROOM.classsession')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSessionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('class_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='CLASSROOM.classsession')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSessionCloze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_with_blank', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('context', models.TextField(blank=True, default='')),
                ('source_span', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('options', models.JSONField(blank=True, default=list)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clozes', to='CLASSROOM.classsession')),
            ],
            options={
                'indexes': [models.Index(fields=['class_session'], name='CLASSROOM_c_class_s_a7332f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='classsessionfeynman',
            index=models.Index(fields=['class_session'], name='CLASSROOM_c_class_s_525e3e_idx'),
        ),
        migrations.AddIndex(
            model_name='classsessionfeynmanattempt',
            index=models.Index(fields=['class_session', 'user', 'feynman'], name='CLASSROOM_c_class_s_c2779f_idx'),
        ),
        migrations.AddIndex(
            model_name='classsessionfeynmanattempt',
            index=models.Index(fields=['score'], name='CLASSROOM_c_score_2f7678_idx'),
        ),
    ]
