# Generated by Django 5.1.5 on 2026-08-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLASSROOM', '0002_alter_classsession_status_classsessionfeynman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='class_covers/'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('recording', 'Recording'), ('stopped', 'Stopped'), ('transcribing', 'Transcribing'), ('ready', 'Ready'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='recording', max_length=20),
        ),
    ]
