# Generated by Django 5.1.5 on 2026-08-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLASSROOM', '0003_classsession_cover_image_alter_classsession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='language',
            field=models.CharField(default='en', max_length=8),
        ),
    ]
