# Generated by Django 5.1.5 on 2025-08-14 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('API', '0003_document_processing_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_imports', to='API.user')),
            ],
        ),
        migrations.CreateModel(
            name='CSVFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_term', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('status', models.CharField(choices=[('still_learning', 'Still Learning'), ('mastered', 'Mastered')], default='still_learning', max_length=20)),
                ('last_reviewed', models.DateTimeField(auto_now=True)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('times_shown', models.PositiveIntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('interval', models.PositiveIntegerField(default=0)),
                ('easiness', models.FloatField(default=2.5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_flashcards', to='API.user')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='CSV.csvimport')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'next_review_at'], name='CSV_csvflas_user_id_7feb19_idx'), models.Index(fields=['user', 'status'], name='CSV_csvflas_user_id_d9242a_idx')],
            },
        ),
    ]
