# Generated by Django 5.1.5 on 2025-08-14 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_document_processing_status'),
        ('CSV', '0002_alter_csvflashcard_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='csvflashcard',
            unique_together={('user', 'source', 'key_term')},
        ),
    ]
