# Generated by Django 5.1.5 on 2025-08-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIDEO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='transcript_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
