# Generated by Django 5.1.5 on 2025-09-03 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VIDEO', '0005_videocloze_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='videocloze',
            new_name='VIDEO_video_video_i_4972c8_idx',
            old_name='VIDEO_videoc_video_id_idx',
        ),
        migrations.RenameIndex(
            model_name='videofeynman',
            new_name='VIDEO_video_video_i_496e36_idx',
            old_name='VIDEO_videof_video_id_idx',
        ),
    ]
