# Generated by Django 5.1.5 on 2025-09-03 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_feynmanattempt_and_more'),
        ('VIDEO', '0006_rename_video_videoc_video_id_idx_video_video_video_i_4972c8_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFeynmanAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('tier', models.CharField(blank=True, default='', max_length=20)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('key_points_coverage', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feynman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='VIDEO.videofeynman')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_feynman_attempts', to='API.user')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feynman_attempts', to='VIDEO.video')),
            ],
            options={
                'indexes': [models.Index(fields=['video', 'user', 'feynman'], name='VIDEO_video_video_i_039232_idx'), models.Index(fields=['score'], name='VIDEO_video_score_1d9f3d_idx')],
            },
        ),
    ]
