# Generated by Django 5.1.5 on 2026-08-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VIDEO', '0008_video_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
