# Generated by Django 5.1.5 on 2025-09-01 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('API', '0004_flashcard_easiness_flashcard_interval_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreStudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('quick', 'Quick'), ('overall', 'Overall')], max_length=20)),
                ('method', models.CharField(choices=[('MCQ', 'MCQ'), ('CLOZE', 'Cloze'), ('FEYNMAN', 'Feynman'), ('MIXED', 'Mixed')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('items_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('percent', models.FloatField(default=0.0)),
                ('passed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='API.user')),
            ],
        ),
        migrations.CreateModel(
            name='CoreXpAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_total', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_active_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xp_account', to='API.user')),
            ],
            options={
                'verbose_name': 'XP Account',
                'verbose_name_plural': 'XP Accounts',
            },
        ),
        migrations.CreateModel(
            name='CoreXpAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_awards', to='CORE.corestudysession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_awards', to='API.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('unlisted', 'Unlisted')], default='private', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='API.user')),
            ],
        ),
        migrations.AddField(
            model_name='corestudysession',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='CORE.space'),
        ),
        migrations.CreateModel(
            name='SpaceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('importance', models.FloatField(default=1.0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='CORE.space')),
            ],
        ),
        migrations.CreateModel(
            name='CoreLearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('mastered', 'Mastered')], default='new', max_length=20)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('times_shown', models.PositiveIntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('interval', models.PositiveIntegerField(default=0)),
                ('easiness', models.FloatField(default=2.5)),
                ('consecutive_passes', models.PositiveIntegerField(default=0)),
                ('last_quality', models.IntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to='API.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'next_review_at'], name='idx_lp_user_next'), models.Index(fields=['user', 'status'], name='idx_lp_user_status'), models.Index(fields=['user', 'content_type', 'object_id'], name='uniq_lp_user_item')],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='CoreAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('MCQ', 'MCQ'), ('CLOZE', 'Cloze'), ('FEYNMAN', 'Feynman'), ('MIXED', 'Mixed')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('correct', models.BooleanField(default=False)),
                ('confidence', models.IntegerField(blank=True, null=True)),
                ('raw_answer', models.TextField(blank=True, null=True)),
                ('ai_score', models.FloatField(blank=True, null=True)),
                ('ai_feedback', models.JSONField(blank=True, null=True)),
                ('quality', models.IntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='API.user')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='CORE.corestudysession')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'session'], name='idx_attempt_user_session')],
            },
        ),
        migrations.AddIndex(
            model_name='corestudysession',
            index=models.Index(fields=['user', 'started_at'], name='idx_session_user_started'),
        ),
        migrations.AddIndex(
            model_name='spaceitem',
            index=models.Index(fields=['space', 'content_type', 'object_id'], name='uniq_space_item'),
        ),
        migrations.AlterUniqueTogether(
            name='spaceitem',
            unique_together={('space', 'content_type', 'object_id')},
        ),
    ]
