# Generated by Django 5.1.5 on 2026-08-07 19:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_document_source_meta'),
        ('CORE', '0003_board_column_card_topic_board_topic_cardresource'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('method', models.CharField(blank=True, default='', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_times', to='CORE.card')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_times', to='CORE.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_times', to='API.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'started_at'], name='CORE_studyt_user_id_23199a_idx'), models.Index(fields=['user', 'topic'], name='CORE_studyt_user_id_bb3c58_idx')],
            },
        ),
    ]
